# Generated by Django 5.1.4 on 2025-01-11 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=255)),
                ('createdAt', models.DateField(default=datetime.datetime.now)),
                ('inStock', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('image', models.CharField(max_length=2083)),
            ],
        ),
    ]
