# Generated by Django 5.1.5 on 2025-01-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
    ]
